import type { ReportDataset } from './types';

export const analyticsFixture: ReportDataset = {
  ledgerEntries: [
    {
      id: 'l1',
      date: '2026-04-08',
      referenceNo: 'GIN-1',
      type: 'purchase',
      particulars: 'Vendor A',
      itemName: 'Cotton',
      itemCategory: 'RAW',
      batchNo: 'RM-001',
      mfgDate: '2026-04-01',
      expiryDate: '2027-04-01',
      receiptQty: 1000,
      issueQty: 0,
      rate: 40,
      remarks: '',
    },
    {
      id: 'l2',
      date: '2026-04-09',
      referenceNo: 'ISS-1',
      type: 'issue',
      particulars: 'Production',
      itemName: 'Cotton',
      itemCategory: 'RAW',
      batchNo: 'RM-001',
      mfgDate: '2026-04-01',
      expiryDate: '2027-04-01',
      receiptQty: 0,
      issueQty: 200,
      rate: 40,
      remarks: '',
    },
  ],
  mrsRecords: [
    { id: 'mrs-1', date: '2026-04-09', batchId: 'batch-1', batchNo: 'FG-001', itemName: 'Cotton', qtyRequested: 300, qtyIssued: 200, status: 'PARTIAL' },
    { id: 'mrs-2', date: '2026-04-09', batchId: 'batch-1', batchNo: 'FG-001', itemName: 'Chemical', qtyRequested: 100, qtyIssued: 100, status: 'CLOSED' },
  ],
  productionBatches: [
    { id: 'batch-1', batchNo: 'FG-001', productName: 'Finished Product A', batchSize: '500', status: 'QA_PENDING', startDate: '2026-04-08', mfgDate: '2026-04-08', expDate: '2028-04-08' },
    { id: 'batch-2', batchNo: 'FG-002', productName: 'Finished Product B', batchSize: '300', status: 'BLOCKED', startDate: '2026-04-07', mfgDate: '2026-04-07', expDate: '2028-04-07' },
  ],
  qaByBatch: [
    { batchId: 'batch-1', qa: { status: 'PENDING', remarks: 'awaiting', approvedBy: '' } },
    { batchId: 'batch-2', qa: { status: 'REJECTED', remarks: 'blocked', approvedBy: 'QA Manager' } },
  ],
  qualityRequests: [
    {
      id: 'qr-1',
      requestNo: 'QREQ-001',
      date: '2026-04-05',
      itemName: 'Cotton',
      batchNo: 'RM-001',
      quantity: 10,
      issueType: 'testing',
      description: 'Routine',
      remarks: '',
      requestedBy: 'QA Lead',
      status: 'pending',
    },
  ],
  proformaInvoices: [
    {
      id: 'pi-1',
      piNo: 'PI-001',
      date: '2026-04-10',
      customerId: 'c1',
      customerName: 'Customer A',
      customerAddress: '',
      items: [{ itemId: 'fg1', itemName: 'Finished Product A', quantity: 500, invoicedQty: 300, rate: 250, amount: 125000 }],
      totalQuantity: 500,
      totalAmount: 125000,
      status: 'partial',
    },
  ],
  invoices: [
    {
      id: 'inv-1',
      invoiceNo: 'INV-001',
      date: '2026-04-11',
      customerId: 'c1',
      customerName: 'Customer A',
      customerAddress: '',
      piId: 'pi-1',
      piNo: 'PI-001',
      items: [{ itemId: 'fg1', itemName: 'Finished Product A', batchNo: 'FG-001', quantity: 300, rate: 250, taxPercent: 18, amount: 75000 }],
      totalQuantity: 300,
      totalAmount: 75000,
      taxAmount: 13500,
      status: 'completed',
    },
  ],
  stockMovements: [
    {
      id: 'mv-1',
      movementNo: 'MOV-001',
      date: '2026-04-09',
      type: 'issue',
      itemName: 'Cotton',
      batchNo: 'RM-001',
      quantity: 200,
      mrsId: 'mrs-1',
      mrsNo: 'MRS-001',
      productionBatchId: 'batch-1',
      productionBatchNo: 'FG-001',
    },
    {
      id: 'mv-2',
      movementNo: 'MOV-002',
      date: '2026-04-10',
      type: 'sampling',
      itemName: 'Cotton',
      batchNo: 'RM-001',
      quantity: 10,
      availableQty: 800,
      fromLocation: 'Store',
      toLocation: 'QC',
    },
  ],
  stockPositions: [
    {
      key: 'Cotton::RM-001',
      itemName: 'Cotton',
      batchNo: 'RM-001',
      qty: 800,
      value: 32000,
      rate: 40,
      expiryDate: '2027-04-01',
      lastMovementDate: '2026-04-10',
    },
  ],
};

